// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mrsufgi/todo_api/internal/domain (interfaces: TodosService)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// MockTodosService is a mock of TodosService interface
type MockTodosService struct {
	ctrl     *gomock.Controller
	recorder *MockTodosServiceMockRecorder
}

// MockTodosServiceMockRecorder is the mock recorder for MockTodosService
type MockTodosServiceMockRecorder struct {
	mock *MockTodosService
}

// NewMockTodosService creates a new mock instance
func NewMockTodosService(ctrl *gomock.Controller) *MockTodosService {
	mock := &MockTodosService{ctrl: ctrl}
	mock.recorder = &MockTodosServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTodosService) EXPECT() *MockTodosServiceMockRecorder {
	return m.recorder
}
